# Generated by Django 5.0.7 on 2026-01-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UKUNDAYEZU Hermogene', max_length=100)),
                ('title', models.CharField(help_text='Your main title/role', max_length=200)),
                ('bio', models.TextField(help_text='Brief bio that will be animated')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('headline_1', models.CharField(default='Full Stack Developer', help_text='First animated headline', max_length=200)),
                ('headline_2', models.CharField(default='Software Engineer', help_text='Second animated headline', max_length=200)),
                ('headline_3', models.CharField(default='Tech Enthusiast', help_text='Third animated headline', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
