# Generated by Django 5.0.7 on 2026-01-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_profile_email_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('degree', models.CharField(help_text='e.g., Bachelor of Science, Diploma, etc.', max_length=200)),
                ('field_of_study', models.CharField(help_text='e.g., Computer Science, Information Technology', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional info about the program', null=True)),
                ('grade', models.CharField(blank=True, help_text='GPA or grade', max_length=10, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
    ]
